Completed prep-css-flexbox exercise -
nsturz/prep-0222-code-solutions pull request #8
Opened 2022-02-25 17:50 UTC by nsturz

2022-02-25 23:33 UTC, thebearingedge requested changes
Hi Nick, just updating this for my records here. Lemme know when the screenshots are available and I'll review again 👍

2022-02-26 01:39 UTC, nsturz commented
<img width="1440" alt="Screen Shot 2022-02-25 at 9 40 30 AM" src="https://user-images.githubusercontent.com/94485412/155823605-1d0ab180-3c76-4c2e-a461-d52a8f57ceaa.png">
<img width="1024" alt="Screen Shot 2022-02-25 at 9 39 16 AM" src="https://user-images.githubusercontent.com/94485412/155823609-de1ec200-23b7-40b9-8058-2fe365573772.png">
<img width="1024" alt="Screen Shot 2022-02-25 at 9 39 08 AM" src="https://user-images.githubusercontent.com/94485412/155823611-ba4c00a6-59de-46e4-9915-c80d2846ac8a.png">

2022-02-26 17:08 UTC, thebearingedge requested changes

2022-02-26 17:08 UTC, thebearingedge commented on prep-css-flexbox/flex-wrap.html
> +      flex-basis: calc(100% / 6)
Hi Nick for each of your HTML documents, be sure to apply the `flex-basis` property to the rule set for `.card-wrapper` instead of the `#card-deck`.

2022-03-02 00:27 UTC, thebearingedge approved these changes

2022-03-02 18:43 UTC, merged